import Footerau from '@/components/au/Footerau';
import type { Metadata } from 'next';
import { DM_Serif_Display, Poppins } from 'next/font/google';

const dmSerifDisplay = DM_Serif_Display({
  variable: '--font-dm-serif',
  subsets: ['latin'],
  weight: '400',
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifDisplay.variable} ${poppins.variable} antialiased`}
      >
        {children}
        <Footerau/>
      </body>
    </html>
  );
}
